name: publish executables

on:
  push:
    branches: [master]
    tags: ["*"]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the source code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: build executable bundles
        run: ./scripts/publish_executables.sh

      - name: update release notes and executables
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # executes only for new release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            builds/*
