name: publish executables
on:
  push:
    branches: [master]
    tags: ["v*"]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the source code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: build executable bundles
        run: ./scripts/publish_executables.sh

      - name: update release notes and executables
        if: startsWith(github.ref, 'refs/tags/') # executes only for new release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            builds/*

      - name: Update executables for master branch changes
        if: startsWith(github.ref, 'refs/heads/master') # executes only for changes in master
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: master
          prerelease: true
          title: "Development Build - master branch"
          files: |
            builds/*.tar.gz
            builds/*.zip
